// Copyright (c) 2024 The horm-database Authors (such as CaoHao <18500482693@163.com>). All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by server/server-cmdline v2.0.6. DO NOT EDIT.
// source: api.proto

package api

import (
	"github.com/horm-database/server/srv"
)

/* *************** Api Definition *************** */

var (
	ServerDesc = &srv.Description{
		Name:  "server.access.api",
		Funcs: []srv.Func{{"Query", Query}},
	}
)
