// Code generated by server/server-cmdline v2.0.6. DO NOT EDIT.
// source: api.proto

package api

import (
	"github.com/horm-database/server/srv"
)

/* *************** Api Definition *************** */

var (
	ServerDesc = &srv.Description{
		Name:  "server.access.api",
		Funcs: []srv.Func{{"Query", Query}},
	}
)
